name: CI Pipeline

on:
  pull_request:
    branches:
      - '*'  # Triggers on pull request to any branch
  schedule:
    - cron: '0 0 * * 0'  # Weekly SAST scan every Sunday at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --use-deprecated=legacy-resolver -r requirements.txt

    - name: Run Pytest
      run: |
        pytest hello.py

    - name: Run Bandit (SAST) - Security Analysis
      run: |
        pip install bandit
        bandit -r . -v
      continue-on-error: false  # Fail the PR if issues are found

    - name: Run Dependency Vulnerability Check (Safety)
      run: |
        pip install safety
        safety check --full-report
      continue-on-error: false  # Fail the PR if vulnerable dependencies are found

    - name: Run Gitleaks (Secrets Scan)
      uses: gitleaks/gitleaks-action@v1
      with:
        config-path: .gitleaks.toml
      continue-on-error: false  # Fail the PR if secrets are found

    - name: Success
      run: echo "All checks passed successfully!"
      if: success()  # This step only runs if all checks pass
